### ISSUE TITLE
error: missing script: webpack-dev-server

### ISSUE THREAD

**Issue by lukemt** [vsavkin/tex#3]
i am trying to run this with `npm run webpack-dev-server` but i get the error-message: `missing script: webpack-dev-server`
any idea? I tried this locally (os x) and on cloud9(linux) and got the same issue

**Comment by pkozlowski-opensource** [comment]
`webpack-dev-server` is not a script but a npm dependency, see: https://github.com/vsavkin/tex/blob/master/angular2/package.json

I suspect that you either didn't do `npm install` or got rather old version of npm

**Comment by lukemt** [comment]
the npm version is  v3.3.12

i actually did do  `npm install`

here is the my output:

```
angular2 [master●] $ npm install
npm WARN EPACKAGEJSON angular2 No description
npm WARN EPACKAGEJSON angular2 No repository field.
npm WARN EPACKAGEJSON angular2 No license field.
angular2 [master] $ npm run webpack-dev-server
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "webpack-dev-server"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12

npm ERR! missing script: webpack-dev-server
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Mainuser/Projekte/angular/tex/angular2/npm-debug.log
```

adn here is the content of `npm-debug.log`:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'webpack-dev-server' ]
2 info using npm@3.3.12
3 info using node@v5.1.0
4 verbose stack Error: missing script: webpack-dev-server
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:147:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:57:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:309:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:343:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
4 verbose stack     at ReadFileContext.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:284:20)
4 verbose stack     at ReadFileContext.callback (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:76:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)
5 verbose cwd /Users/Mainuser/Projekte/angular/tex/angular2
6 error Darwin 14.5.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "webpack-dev-server"
8 error node v5.1.0
9 error npm  v3.3.12
10 error missing script: webpack-dev-server
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by lukemt** [comment]
I've now updated npm to version 3.5. but it didn't help.

**Comment by honeyjie** [comment]
I got the same problem
➜  groceryList git:(master) ✗ npm run node_modules/.bin/webpack-dev-server
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/Cellar/node/7.7.3/bin/node" "/usr/local/bin/npm" "run" "node_modules/.bin/webpack-dev-server"
npm ERR! node v7.7.3
npm ERR! npm  v4.1.2

npm ERR! missing script: node_modules/.bin/webpack-dev-server

**Comment by praWINK** [comment]
I also have this same issue anyone solved that.......
